#!/bin/sh

fancy_echo() {
  local fmt="$1"; shift

  # shellcheck disable=SC2059
  printf "\\n$fmt\\n" "$@"
}

append_to_zshrc() {
  local text="$1" zshrc
  local skip_new_line="${2:-0}"

  if [ -w "$HOME/.zshrc.local" ]; then
    zshrc="$HOME/.zshrc.local"
  else
    zshrc="$HOME/.zshrc"
  fi

  if ! grep -Fqs "$text" "$zshrc"; then
    if [ "$skip_new_line" -eq 1 ]; then
      printf "%s\\n" "$text" >> "$zshrc"
    else
      printf "\\n%s\\n" "$text" >> "$zshrc"
    fi
  fi
}

# shellcheck disable=SC2154
trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT

set -e

if [ ! -d "$HOME/.bin/" ]; then
  mkdir "$HOME/.bin"
fi

if [ ! -f "$HOME/.zshrc" ]; then
  touch "$HOME/.zshrc"
fi

# shellcheck disable=SC2016
append_to_zshrc 'export PATH="$HOME/.bin:$PATH"'

HOMEBREW_PREFIX="/usr/local"

if [ -d "$HOMEBREW_PREFIX" ]; then
  if ! [ -r "$HOMEBREW_PREFIX" ]; then
    sudo chown -R "$LOGNAME:admin" /usr/local
  fi
else
  sudo mkdir "$HOMEBREW_PREFIX"
  sudo chflags norestricted "$HOMEBREW_PREFIX"
  sudo chown -R "$LOGNAME:admin" "$HOMEBREW_PREFIX"
fi

update_shell() {
  local shell_path;
  shell_path="$(command -v zsh)"

  fancy_echo "Changing your shell to zsh ..."
  if ! grep "$shell_path" /etc/shells > /dev/null 2>&1 ; then
    fancy_echo "Adding '$shell_path' to /etc/shells"
    sudo sh -c "echo $shell_path >> /etc/shells"
  fi
  sudo chsh -s "$shell_path" "$USER"
}

case "$SHELL" in
  */zsh)
    if [ "$(command -v zsh)" != '/usr/local/bin/zsh' ] ; then
      update_shell
    fi
    ;;
  *)
    update_shell
    ;;
esac

if ! command -v brew >/dev/null; then
  fancy_echo "Installing Homebrew ..."
    curl -fsS \
      'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby

    append_to_zshrc '# recommended by brew doctor'

    # shellcheck disable=SC2016
    append_to_zshrc 'export PATH="/usr/local/bin:$PATH"' 1

    export PATH="/usr/local/bin:$PATH"
fi

if brew list | grep -Fq brew-cask; then
  fancy_echo "Uninstalling old Homebrew-Cask ..."
  brew uninstall --force brew-cask
fi

fancy_echo "Updating Homebrew formulae ..."
brew update --force # https://github.com/Homebrew/brew/issues/1151
brew bundle --file=- <<EOF
tap "thoughtbot/formulae"
tap "homebrew/services"
tap "universal-ctags/universal-ctags"
tap "caskroom/cask"
tap "caskroom/fonts"

# Unix
brew "ack"
brew "coreutils"
brew "fd"
brew "fzf"
brew "gcc"
brew "git"
brew "gpg"
brew "grep"
brew "libgcrypt"
brew "libssh2"
brew "neovim"
brew "openssl"
brew "rcm"
brew "reattach-to-user-namespace"
brew "the_silver_searcher"
brew "tmux"
brew "tree"
brew "universal-ctags", args: ["HEAD"]
brew "vim"
brew "watch"
brew "watchman"
brew "zsh"
brew "zsh-completions"

# Image/metadata/pdf manipulation
brew "ghostscript"
brew "graphicsmagick"
brew "imagemagick"
brew "exiftool"
brew "source-to-image"

# Development Tools
brew "exercism"
brew "make"
brew "readline"
brew "xz"
brew "zlib"

# Databases
brew "mongodb"
brew "redis"
brew "sqlite3"

# Applications
cask "1password"
cask "alfred"
cask "atom"
cask "blender"
cask "chrome-devtools"
cask "dash"
cask "day-o"
cask "docker"
cask "dropbox"
cask "firefox"
cask "font-hack-nerd-font"
cask "gitkraken"
cask "google-chrome"
cask "google-cloud-sdk"
cask "insomnia"
cask "iterm2"
cask "macdown"
cask "slack"
cask "spotify"
cask "studio-3t"
cask "visual-studio-code"

# Fonts
cask "font-hack-nerd-font"
EOF

fancy_echo "Installing oh my zsh..."
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

fancy_echo "Installing spaceship prompt..."
ZSH_CUSTOM_THEMES_PATH=$HOME/.oh-my-zsh/custom/themes
if [ ! -L "$ZSH_CUSTOM_THEMES_PATH/spaceship.zsh-theme" ]; then
  if [ ! -d "$ZSH_CUSTOM_THEMES_PATH/spaceship-prompt/" ]; then
    git clone https://github.com/denysdovhan/spaceship-prompt.git "$ZSH_CUSTOM_THEMES_PATH/spaceship-prompt"
  fi
  ln -s "$ZSH_CUSTOM_THEMES_PATH/spaceship-prompt/spaceship.zsh-theme" "$ZSH_CUSTOM_THEMES_PATH/spaceship.zsh-theme"
else 
  fancy_echo "Spaceship theme is already installed!"
fi

fancy_echo "Installing zsh plugins..."
ZSH_CUSTOM_PLUGINS_PATH=$HOME/.oh-my-zsh/custom/plugins
if [ ! -d "$ZSH_CUSTOM_PLUGINS_PATH/zsh-syntax-highlighting" ]; then
  fancy_echo "Installing zsh-syntax-highlighting..."
  git clone https://github.com/zsh-users/zsh-syntax-highlighting.git "$ZSH_CUSTOM_PLUGINS_PATH/zsh-syntax-highlighting"
fi

if [ ! -d "$ZSH_CUSTOM_PLUGINS_PATH/zsh-autosuggestions" ]; then
  fancy_echo "Installing zsh-autosuggestions..."
  git clone https://github.com/zsh-users/zsh-autosuggestions "$ZSH_CUSTOM_PLUGINS_PATH/zsh-autosuggestions"
fi

if [ ! -d "$ZSH_CUSTOM_PLUGINS_PATH/gitgo" ]; then
  fancy_echo "Installing gitgo..."
  git clone https://github.com/ltj/gitgo.git "$ZSH_CUSTOM_PLUGINS_PATH/gitgo"
fi

fancy_echo "Configuring asdf version manager..."
if [ ! -d "$HOME/.asdf" ]; then
  git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.5.0
  append_to_zshrc "source $HOME/.asdf/asdf.sh" 1
fi

fancy_echo "Installing vim.plug..."
if [ ! -f "$HOME/.local/share/nvim/site/autoload/plug.vim" ]; then
  curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

install_asdf_plugin() {
  local name="$1"
  local url="$2"

  if ! asdf plugin-list | grep -Fq "$name"; then
    asdf plugin-add "$name" "$url"
  fi
}

install_asdf_language() {
  local language="$1"
  local version
  version="$(asdf list-all "$language" | grep -v "[a-z]" | tail -1)"

  if ! asdf list "$language" | grep -Fq "$version"; then
    asdf install "$language" "$version"
    asdf global "$language" "$version"
  fi
}

gem_install_or_update() {
  if gem list "$1" --installed > /dev/null; then
    gem update "$@"
  else
    gem install "$@"
  fi
}

# shellcheck disable=SC1090
source "$HOME/.asdf/asdf.sh"
install_asdf_plugin "ruby" "https://github.com/asdf-vm/asdf-ruby.git"
install_asdf_plugin "nodejs" "https://github.com/asdf-vm/asdf-nodejs.git"
install_asdf_plugin "elixir" "https://github.com/asdf-vm/asdf-elixir.git"
install_asdf_plugin "python" "https://github.com/tuvistavie/asdf-python.git"

fancy_echo "Installing latest Ruby..."
install_asdf_language "ruby"
gem update --system
gem_install_or_update "bundler"
number_of_cores=$(sysctl -n hw.ncpu)
bundle config --global jobs $((number_of_cores - 1))

fancy_echo "Installing additional Ruby gems..."
gem_install_or_update "tmuxinator"

fancy_echo "Installing latest Node..."
bash "$HOME/.asdf/plugins/nodejs/bin/import-release-team-keyring" 
install_asdf_language "nodejs"

fancy_echo "Installing latest Elixir..."
install_asdf_language "elixir"

fancy_echo "Installing latest Python..."
install_asdf_language "python"

fancy_echo "Enable python 3 interface..."
pip install neovim

if [ -f "$HOME/.laptop.local" ]; then
  fancy_echo "Running your customizations from ~/.laptop.local ..."
  # shellcheck disable=SC1090
  . "$HOME/.laptop.local"
fi


